server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: web-security-shield

  # Database sozlamalari (H2 - oddiy test DB)
  datasource:
    url: jdbc:h2:mem:security_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 Console (development uchun)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA sozlamalari
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Thymeleaf (HTML template engine)
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# Xavfsizlik sozlamalari
security:
  # Rate Limiting sozlamalari
  rate-limit:
    requests-per-minute: 10
    block-duration-minutes: 5

  # IP Blocking sozlamalari
  ip-blocking:
    max-failed-attempts: 5
    block-duration-hours: 1

  # XSS himoya sozlamalari
  xss-protection:
    enabled: true
    block-mode: true

  # SQL Injection himoya sozlamalari
  sql-injection:
    enabled: true
    strict-mode: false

# Logging sozlamalari
logging:
  level:
    uz.edu.security: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/security.log